name: Update Discord Message

on:
  schedule:
    # Wednesday 12:00 PM PST
    # - cron: "0 20 * * WED"
    - cron: "*/5 * * * *"

jobs:
  update-message:
    runs-on: ubuntu-latest
    environment: action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm run start
        env:
          DISCORD_API_URL: ${{secrets.DISCORD_API_URL}}
          DISCORD_APPLICATION_ID: ${{secrets.DISCORD_APPLICATION_ID}}
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
          DISCORD_FIRE_ID: ${{secrets.DISCORD_FIRE_ID}}
          DISCORD_PUBLIC_KEY: ${{secrets.DISCORD_PUBLIC_KEY}}
          DISCORD_REDIRECT_URI: ${{secrets.DISCORD_REDIRECT_URI}}
          DISCORD_SERVER_ID: ${{secrets.DISCORD_SERVER_ID}}
          DISCORD_SHAM_ID: ${{secrets.DISCORD_SHAM_ID}}
          DISCORD_TYSON_ID: ${{secrets.DISCORD_TYSON_ID}}
