name: Update Discord Message

on:
  schedule:
    # Run every Tuesday at 00:00 UTC
    - cron: "5 1 * * SUN"

jobs:
  update-message:
    runs-on: ubuntu-latest
    environment: action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm run
